### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by sveip** [YiannisBourkelis/Andama-Remote-Desktop#1]
Is this project still planned to be implemented?

**Comment by YiannisBourkelis** [comment]
Yes, I am working on it. Currently I am trying to figure out how to capture a screenshot from the windows log on screen, or when the UAC prompt appears. 
Do you know how can this be done?

**Comment by antton** [comment]
Hello @YiannisBourkelis did you get any advance on UAC prompt screen?

Anyway, the software is working fantastic even if it's not valid with this "restriction".

I can't help you because I don't even know how to skip it!

Cheers

**Comment by YiannisBourkelis** [comment]
Thank you antton,
I have done some research on the UAC prompt issue however I have not fixed it yet.

**Comment by antton** [comment]
I found another bug, when you connect to a remote windows computer at least from macos, and when you end up working on it and close the connection, the keyboard from the remote windows computer get useless and you need to logout from the session or restart the computer to get it working properly again.

If you release a new version, I'd lovely try it.

Thanks for your hard work!!

**Comment by YiannisBourkelis** [comment]
Can you help me reproduce this issue?
What is the version of windows you are connecting to? Windows 10/7/Vista/XP? x86/x64?

**Comment by antton** [comment]
Osx el capitan connecting to windows 10 x64.

Let me know if I can help you with anything else ;)

**Comment by YiannisBourkelis** [comment]
Thank you antton, I will try to reproduce it when I will have a windows 10 x64 machine available.

**Comment by antton** [comment]
Hello again, 

I install the linux client on Ubuntu 16.04 and is working perfectly from osx -> linux.

You have an awesome software, I don't understand why is not soo popular, but anyway.

It would be nice to let decide which proxy server use to make it work, actually I see that is using your personal proxy server 'mailgate.filoxeni.com'. 

I'm going to try to compile the proxy and then try to compile the client with Qt.

I'll let you know ;)

Thanks!

**Comment by YiannisBourkelis** [comment]
Yes you can change the proxy address from https://github.com/YiannisBourkelis/Andama-Remote-Desktop/blob/master/src/Andama/clientserver.cpp , line 930 to whatever domain the proxy is located.

To compile AndamaProxy to a linux machine, just copy this file: https://github.com/YiannisBourkelis/Andama-Remote-Desktop/blob/master/src/AndamaProxy/main.cpp
to your server and compile it:
g++  main.cpp -o main.out -pthread -std=c++11

**Comment by antton** [comment]
Great!

**Comment by marcelodias1806** [comment]
Dear,

I wanted to contribute to the project by putting the language in Portuguese (Brazil). It's possible?

Best Regards

**Comment by YiannisBourkelis** [comment]
Thank you marcelodias.
Yes, translation in Portuguese is possible. I will check the Qt documentation to find out the best way to do it and I will let you know until Tuesday.

To recompile and run the application you should download Qt for open source from this link: [https://www.qt.io/download/](url) on each platform.

For the translation you can use your linux machine and Qt. I will send you more details soon. I just have to find out the best way to do it.

**Comment by antton** [comment]
I will wait you indications as well and translate it into basque and spanish ;)

**Comment by YiannisBourkelis** [comment]
@marcelodias1806 and @antton thank you very much for your offer on translating Andama. I created two new threads for the translations.

From English to Portuguese: [https://github.com/YiannisBourkelis/Andama-Remote-Desktop/issues/2](https://github.com/YiannisBourkelis/Andama-Remote-Desktop/issues/2)

From English to Spanish/Basque: [https://github.com/YiannisBourkelis/Andama-Remote-Desktop/issues/3](https://github.com/YiannisBourkelis/Andama-Remote-Desktop/issues/3)

**Comment by johnkeel-obsidian** [comment]
How are you compiling with Windows?
QT MinGW 32Bit?
QT MSVC ?

I will try to contribute with a better UI.

**Comment by YiannisBourkelis** [comment]
Hi @johnkeel-obsidian,
on windows I use the MSVC compiler that comes with Visual Studio.
Please clone the "develop" branch because I have done some changes on the UI from the master branch. Thank you for considering contributing to the project :-)

**Comment by johnkeel-obsidian** [comment]
Thank you for your fast reply.
Ok i changed my Kit like this:
QT 5.9.0 MSVC2017 64bit
It did compile.
Now im not sure if i understand how the software works, since i get a empty "LOCAL COMPUTER" info, no ID and no PASS.

Regarding the looks, can i go modern flat on it? I will make you a preview.

**Comment by YiannisBourkelis** [comment]
@johnkeel-obsidian this is happening because the proxy is down. I am fixing it now, maybe in 10 minutes it will work. I will send you a message here when the proxy server will be up.

**Comment by YiannisBourkelis** [comment]
@johnkeel-obsidian ok the proxy server is up and running. Andama should now get an ID

**Comment by YiannisBourkelis** [comment]
@johnkeel-obsidian yes I believe modern flat will look nice. I will wait for a screenshot.

**Comment by johnkeel-obsidian** [comment]
Yeap it does.
I´m starting to understand this! I can compile the proxy to setup my own testing server too right?
Nice... this seems to be well thought, congrats man.
Can you please tell me what the UPNP return error code: 500, is?

**Comment by YiannisBourkelis** [comment]
I use the uPnP protocol to open port forwarding on the router so that a direct (p2p) connection between the 2 computers will be established. This reduces the extra latency introduced when using the proxy server. Currently the uPnP code is work in progress, that is because you are receiving this error 500. Maybe if you login into your router and enable uPnP this error will be gone. 

You can compile the AdamaProxy yourself if you want to test it locally. 
To make Andama work on your local computer and your local Andama Proxy server you should:
1. In Andama > open clientserver.cpp > uncomment line 750: SERVER = gethostbyname("localhost");
2. In Andama > open clientsocket.cpp > uncomment line 90: SERVER = gethostbyname("localhost");
3. Compile and run AndamaProxy
4. Compile nd run Andama. It should connect to your local proxy server

**Comment by johnkeel-obsidian** [comment]
Wow thanks!
Really amazing work.
Tomorrow ill do my first GUI so you can check...

**Comment by YiannisBourkelis** [comment]
Thank you @johnkeel-obsidian !! :-)

**Comment by johnkeel-obsidian** [comment]
sorry to disturb you but i can´t still make it work.
It connects to my proxy, the two units get the IDs and PASS, then when i do a connection it seems to trigger it fine, minimizes on host but nothing shows up on the unit which is connecting.
On the laptop i use to connect it should be showing the remote system but it does not.
If i close the app on the host it says there´s a connected user and all.
Any idea?

**Comment by johnkeel-obsidian** [comment]
Btw, this is looping in the host (it´s the app output):

JPG conversion :2ms
vimgbytes creation :0ms
screenshotsWorker::sendScreenshot ALL :2ms
this->prepareAndSendScreenshotDiff() - ALLx2 :6ms
screenshotWorker::run-isDirty - ALL :6ms

But the app is not showing the actual remote window

**Comment by YiannisBourkelis** [comment]
- In order to work correctly you should have Qt framework installed on both machines.
- Do a qmake / clean / rebuild just in case.
- If you are connecting to the remote machine using windows remote desktop, the remote desktop window should be open (not minimized)
- Try to use the default andama proxy, not your local.

**Comment by johnkeel-obsidian** [comment]
Checked all of that
I think the printscreen is not being sent:

Machine 1:
IMAGE DIFF BYTES RECIEVED:4
... nothing else

Machine 2 Log:
Warning: QPainter::begin: Paint device returned engine == 0, type: 3 (:0, )
WArning: QImage::scaled: Image is a null image (:0, )
(loops)

I´m now trying connecting only with proxy mode.

**Comment by johnkeel-obsidian** [comment]
AHHHH!!! solved!!!!
Finally i can start working on it!!!
My bad, one of the units was missing QT Framework files... DUH

**Comment by YiannisBourkelis** [comment]
Great!

**Comment by neuronet77** [comment]
Hi YiannisBourkelis!

Thanks a lot for the work you've put into this project so far.

I stumpled across it last night while trying to find a good alternative for remote support instead of this high prices commercial systems like T***V***** & Co.

Right now I'm on "enhancing" the proxy server to store recent session data in a local MySql database to be able to see open connections via support panel.

As soon as this is done, I'll be happily willing to share the code here with you guys.

Meanwhile, I'm trying to get the main application compiled on Windows.

I have the choice between VS2010, VS2012 and VS2013. Any advice on how to get it compiled properly?

Thanks a lot in advance.

**Comment by neuronet77** [comment]
C:\Users\neuronet\Downloads\andama\Andama-Remote-Desktop-master\Andama-Remote-Desktop-master\src\Andama\moc_clientserver.cpp:81: error: C2660: 'clientserver::sig_messageRecieved' : function does not take 3 arguments

I get this error message on the master branch when trying to compile in QT Creator on Windows

**Comment by dougrinkin** [comment]
Hi YiannisBourkelis,

I wanted to know if the proxy server is still down if so when will it be up?  Because I am getting a cannot connect to proxy error.  Also was wondering can I setup a proxy out on the internet that is live that I can use for testing between two computers in different locations?  I would setup the proxy Server in  an AWS instance.  What platform do you recommend for this? Hope to hear from you soon.

Thanks,

Doug

**Comment by neuronet77** [comment]
@dougrinkin 

YiannisBourkelis wrote further up in this thread:

Yes you can change the proxy address from https://github.com/YiannisBourkelis/Andama-Remote-Desktop/blob/master/src/Andama/clientserver.cpp , line 930 to whatever domain the proxy is located.

To compile AndamaProxy to a linux machine, just copy this file: https://github.com/YiannisBourkelis/Andama-Remote-Desktop/blob/master/src/AndamaProxy/main.cpp
to your server and compile it:
g++ main.cpp -o main.out -pthread -std=c++11

This solution works to set up your own proxy

**Comment by dougrinkin** [comment]
Hi Neuronet77,

So my question now is how do I get it the MACOsx version of Andama to recognize the new proxy server?  What line on the code do I need to change for this?  Also if I use QT open source with this work to compile it?


Thanks,

Doug

**Comment by dougrinkin** [comment]
Hi Neuronet77

Also what is the command to recompile the MAC OSX Andama App.

Thanks,

Doug

**Comment by neuronet77** [comment]
Hi @dougrinkin ,

you need qt for OSX installed

"brew install qt"

Then you should be able to compile it via qmake.
Just change the proxy address in line 930 from

SERVER = gethostbyname("mailgate.filoxeni.com");

to

SERVER = gethostbyname("yourproxy.yourdomain.com");

**Comment by YiannisBourkelis** [comment]
@neuronet77 I am using Visual Studio 2015 to compile on windows. I am also planning to implement a session data storage mechanism probably using mysql, mainly for being able to keep the same unique ID, even if the user closes and re-opens the application. Now it takes a new ID each time. However a new ID each time the application starts is a good thing for people how are concerned about their privacy.

**Comment by YiannisBourkelis** [comment]
@dougrinkin probably tomorrow or the day after tomorrow the server will be up and running. I prefer a linux machine for the andama proxy server. Currently the server I am using is an ubuntu x64 minimal server. However the proxy server compiles fine on both windows and osx.

**Comment by sveip** [comment]
Wouldn't it be easier to make a prompt or similar to enter the server
address on startup (if you want to keep it simple with minimal changes)? Or
even better make a settings menu where address can be chosen.

2017-08-25 3:38 GMT+02:00 dougrinkin <notifications@github.com>:

**Comment by YiannisBourkelis** [comment]
@dougrinkin I am using Qt 5.7.1 but it should also compile on newer versions.
@sveip yes, a simple and easy to use solution would be to use the QSettings class, and load some application settings (like proxy server address and port) from an .ini file located at the path where the Andama executable is located.

**Comment by dougrinkin** [comment]
Hi Yiannis,

I wanted to ask you if it is the open source or commercial version of QT 5.7.1 that you are using?

Thanks 

Doug

**Comment by dougrinkin** [comment]
Also one more quick question, what are are the files or files and pralines that control the name of the app as it is displayed when the program launches that say Andama at the top out of curiosity?

Thanks 

Doug

**Comment by neuronet77** [comment]
@YiannisBourkelis : I can provide you a VPS if you would like

**Comment by dougrinkin** [comment]
Hi Yiannis,

 

What is a VPS sorry for the dumb question sir…I really appreciate all of your help I love your product is really great.

 

Best Regards,

 

Doug Rinkin

**Comment by dougrinkin** [comment]
Yiannis,

 

I would love a VPS that would be great.

 

Thanks,

 

Doug Rinkin

**Comment by neuronet77** [comment]
@dougrinkin 

https://en.wikipedia.org/wiki/Virtual_private_server

**Comment by dougrinkin** [comment]
Thank you for the information :) I would love a VPS  that would be very helpful.

 

Thanks,

 

Doug

**Comment by dougrinkin** [comment]
YiannisBourkelis,

 

How long will it take for access to the VPS?

 

Thanks,

 

Doug

**Comment by neuronet77** [comment]
I have just emailed @YiannisBourkelis the SSH logins for a VPS he can use for this project. I hope this will help everybody.

**Comment by dougrinkin** [comment]
Yeah that is awesome!

**Comment by dougrinkin** [comment]
Neuronet77,

 

What version of QT do you use? The open source version or the commercial version?

 

Thanks,

 

Doug

**Comment by marcelodias1806** [comment]
@YiannisBourkelis how are you?

I finished a full translation of Andama, how do I put it here not Github and how do I compile Andama in Portuguese?

My computer is running Linux CentOS 7 and QT is already installed.

**Comment by neuronet77** [comment]
@dougrinkin 
I'm using 5.9.1 in the open source edition

**Comment by dougrinkin** [comment]
Ok, weird I am getting mouse.cpp errors when trying to compile it any ideas what might be causing this? I am using the same version you are.

 

Thanks,

 

Doug

**Comment by dougrinkin** [comment]
Neuronet77, thank you for the information, you have been very very helpful.  I do have some more questions for you in the future probably.

 

Thanks,

 

Doug Rinkin

**Comment by dougrinkin** [comment]
Hi YiannisBourkelis,

 

Does your version of code compile on MACOSX Sierra? What is the latest version it will compile for, for MAC OSX?  Does anyone have a newer commit of this code that will compile on sierra?

 

Thanks,

 

Doug

**Comment by dougrinkin** [comment]
YiannisBourkelis 

I seem to be getting some errors when trying to compile Andama.  It acts like it is going to build the file however after trying to compile it with QT 5.9.1 on MAC OSX Sierra it does not seem to be creating a usable .APP for OSX it there a link to a newer location of code? or perhaps I might be doing something wrong please see the errors below:

/Users/dougrinkin/Downloads/DougDevProject-master/src/Andama/mousekeyb/MouseMac.cpp:44: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef event = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(x, y), 0 /*ignored*/);
                       ^~~~~~~~~~~~~~~~~~~~~~~/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(


                                ^/Users/dougrinkin/Downloads/DougDevProject-master/src/Andama/mousekeyb/MouseMac.cpp:84: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef event = CGEventCreateMouseEvent(NULL, eventType, CGPointMake(mousePos.x(), mousePos.y()), 0 /*ignored*/);
                       ^~~~~~~~~~~~~~~~~~~~~~~
/Users/dougrinkin/Downloads/DougDevProject-master/src/Andama/mousekeyb/MouseMac.cpp:101: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef eventPress = CGEventCreateMouseEvent(NULL, eventTypeMouseDown, CGPointMake(mousePos.x(), mousePos.y()), 0 /*ignored*/);
                            ^~~~~~~~~~~~~~~~~~~~~~~/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^

**Comment by dougrinkin** [comment]
YiannisBourkelis

I am having a heck of a time trying to compile the MAC OSX APP to a working app.  I am using 5.9.1 QT Commerical.  I posted the error problems I was getting with the mouse.cpp file errors.  What am I doing wrong I would be forever in-debted to you if you gave me some advice.

Thanks,

**Comment by dougrinkin** [comment]
YiannisBourkelis,

Hi it's Doug again,  I have been talking to a few of my colleagues and we are working on an open source project that can utilize Andama.  However is it possible to discuss in a more private forum than this Github.  My email address is dr@caringisthecause.com . Please contact me when ever you may be free.  I am looking forward to speaking with you soon.

Sincerely,

Doug

**Comment by dougrinkin** [comment]
Hi does anyone know why when compiling Andama you get MacMouse.cpp errors.  I get about errors like this right before it goes to compile the code. Anyone have any suggestions?

**Comment by YiannisBourkelis** [comment]
@dougrinkin yes, in latest Xcode these compile errors seem to appear in mouse.cpp. I have not tried solve it because I am using a previous version of macOSX sdk (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk)

**Comment by neuronet77** [comment]
@YiannisBourkelis 
You got my mail with the server credentials?

**Comment by YiannisBourkelis** [comment]
@neuronet77  yes, thank you very much! I will reply to you by email later tonight, I am just too busy at the moment

**Comment by neuronet77** [comment]
@YiannisBourkelis 
No rush :D

**Comment by YiannisBourkelis** [comment]
@marcelodias1806 Thank you for the Portuguese translation! Have you followed the guide as described here? [](http://www.andama.org/translation-guide  )

**Comment by dougrinkin** [comment]
Hi Yiannis,

Is there any chance you could turn the proxy up tomorrow?  I would like to try to do some testing. I am working on setting up my own but for the time being that would be great.

thanks,

Doug

**Comment by YiannisBourkelis** [comment]
@dougrinkin yes, it is already up, but it might take the domain some time to propagate. Do a restart of your machine just in case, to refresh your DNS cache.

**Comment by dougrinkin** [comment]
Hi All

Anyone been able to transmit audio over Andama Remote Desktop or does anyone have a plugin that will do this?

Thanks,

Doug

**Comment by YiannisBourkelis** [comment]
@dougrinkin audio streaming is not yet implemented in andama
