### ISSUE TITLE
Inform users of their GPL rights

### ISSUE THREAD

**Issue by shiftee** [YiannisBourkelis/Andama-Remote-Desktop#21]
In some cases it is useful to send an Andama binary to someone for remote support.

As Andama is under the GPL we are obliged to inform them of their rights to the source etc.

Can we add a line of text to the main window which takes care of this for us?

Something like "Andama is Free Software distributed under the GPL"

Ideally, GPL should be a hyper-link. Clicking on it would open a dialog window which displays the license text.

The text "Andama" could also be a hyperlink, linking to andama.org or directly to the source on github

**Comment by YiannisBourkelis** [comment]
@shiftee If you right-click on the main window, there is an about screen with the GPL license and the related links. Is this ok?

**Comment by shiftee** [comment]
I'm not sure if would be visible enough for a court of law but it will certainly do for now
