### ISSUE TITLE
The application fails when I press a key!

### ISSUE THREAD

**Issue by eduardoc25** [YiannisBourkelis/Andama-Remote-Desktop#31]
When I press a key the application fails immediately, from linux client to linux, windows to windows client, as cross linux to windows or windows to linux.
### Client dump:
```
[2019-02-12 01:39:43.874679] 140505895663360----------> EXCEPTION ********  Synevh exception stin arxi [CMD_PROTOCOL], sto dostuff while loop:  std::exception
----------> EXCEPTION ********  Synevh exception stin arxi [CMD_PROTOCOL], sto dostuff while loop: std::exception
----> throw EXCEPTION IN int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message). Bytes send not equal to bytes expected.
[2019-02-12 01:39:43.874697] 140506961012480 ###### [source: int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message)]  displayErrno: Descriptor de fichero erróneo
----------> EXCEPTION ********  Synevh exception stin arxi [CMD_PROTOCOL], sto dostuff while loop: std::exception
[2019-02-12 01:39:43.874620] 140506927441664 ###### [source: int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message)]  displayErrno: Descriptor de fichero erróneo
----------> EXCEPTION ********  Synevh exception stin arxi [CMD_PROTOCOL], sto dostuff while loop: std::exception
###### [source: int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message)]  displayErrno: Descriptor de fichero erróneo
thread done![2019-02-12 01:39:43.874625] 140508485572352 ###### [source: int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message)]  displayErrno: Descriptor de fichero erróneo
----------> EXCEPTION ********  Synevh exception stin arxi [CMD_PROTOCOL], sto dostuff while loop: std::exception
 New client accepted. Kalw accept_client_messages while loop se neo thread.
[2019-02-12 01:39:43.874629] 140506474432256 ###### [source: int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message)]  displayErrno: Descriptor de fichero erróneo
 New client accepted. Kalw accept_client_messages while loop se neo thread.
----------> EXCEPTION ********  Synevh exception stin arxi [CMD_PROTOCOL], sto dostuff while loop: std::exception
----------> EXCEPTION ********  Synevh exception stin arxi [CMD_PROTOCOL], sto dostuff while loop: std::exception
```
### Proxy Server dump:
```
Remote computer p2p port: 0
----------> Client heartbeat timeout
[2019-02-12 01:39:31.192297] 140575773628160 ###### [source: void dostuff(int newsockfd) - [MAIN command loop] - [cmd_bytes_recv == -1]]  displayErrno: Connection reset by peer
----> throw EXCEPTION IN int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message). Bytes send not equal to bytes expected.
[2019-02-12 01:39:31.197707] 140575782020864 ###### [source: int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message)]  displayErrno: Bad file descriptor
----------> EXCEPTION ********  Synevh exception sto dostuff while loop: ----> throw EXCEPTION IN int clientserver::_sendmsgPlain(int socketfd, const std::vector<char> &message). Bytes send not equal to bytes expected.
[2019-02-12 01:39:31.197857] 140575782020864 ###### [source: ----------> EXCEPTION dostuff loop]  displayErrno: Bad file descriptor
[2019-02-12 01:39:31.200533] 140575782025024 New client accepted. Kalw dostuff while loop se neo thread. Client port:14005
Will recieve protocol info
examining client protocol
examining client protocol. app version and protocol version ok
[1] client IP:218183946
[2019-02-12 01:39:31.200949] 140575782020864 232550 CMD_PROTOCOL >  Client ID created and sent to client.
Client IP:10.57.1.13
upnp port for client with id:232550 is:17333
[2019-02-12 01:39:43.869403] 140575782025024 New client accepted. Kalw dostuff while loop se neo thread. Client port:14517
Will recieve protocol info
examining client protocol
examining client protocol. app version and protocol version ok
[1] client IP:218183946
[2019-02-12 01:39:43.869925] 140575773628160 870734 CMD_PROTOCOL >  Client ID created and sent to client.
Client IP:10.57.1.13

```
PD: Proxy Server is compiled and run in Archlinux, all machines is still down the firewall!

**Comment by YiannisBourkelis** [comment]
@eduardoc25 Andama proxy is up and running. Can you try again the Andama develop branch?

**Comment by eduardoc25** [comment]
@YiannisBourkelis I have downloaded the source and compiled it, but it still does not seem to connect, please look at the capture
![screenshot_20190213_211429](https://user-images.githubusercontent.com/6886712/52753210-81470c00-2fd4-11e9-9230-3f3e564c6109.png)

**Comment by YiannisBourkelis** [comment]
@eduardoc25 what is the value of PROXY_PORT_NUMBER ? It is located inside ...src/Shared/AndamaHeaders/shared_constants.h , line 4 . Should be: **const int PROXY_PORT_NUMBER = 80**

**Comment by eduardoc25** [comment]
@YiannisBourkelis , That's right, that's the port, please look at the attachment.
![screenshot_20190213_214605](https://user-images.githubusercontent.com/6886712/52754328-edc40a00-2fd8-11e9-9404-cf74c62dfa46.png)

**Comment by YiannisBourkelis** [comment]
@eduardoc25 strange. Works fine on osx and windows. I do not have a linux machine to test it now...
Maybe you could debug to figure out why this is happening. Does the error appear after the ::connect command on line 150 of client socket.cpp?

**Comment by eduardoc25** [comment]
@YiannisBourkelis , I'm sorry, it was my thing !, I've pipped it on my DNS server, it did not resolve the ip indicated so it did not connect. Now I have tried again with my other computer (windows) and the application still crashes when I press any key.
![screenshot_20190213_224405](https://user-images.githubusercontent.com/6886712/52756779-48f9fa80-2fe1-11e9-815e-96b8676811ec.png)

**Comment by YiannisBourkelis** [comment]
@eduardoc25 maybe you are missing openssl. Did you build it? If not follow the guide inside Andama.pro file.
OpenSSL is included inside the OpenSSL-1.1.0g folder.

For linux:
# go inside OpenSSL-x.x folder using the terminal
# type:
# 1)    ./config
# 2)    make clean
# 3)    make
# this should compile openssl on linux

Then qmake/clean/rebuild Andama

**Comment by YiannisBourkelis** [comment]
@eduardoc25 
windows compile guide:
install activeperl - https://www.activestate.com/activeperl
install nasm - http://www.nasm.us/
go inside OpenSSL-x.x folder from visual studio 2010 command line prompt
type :
1)    perl.exe Configure VC-WIN32
2)    nmake clean
3)    nmake
this should compile openssl on windows

**Comment by eduardoc25** [comment]
> @eduardoc25 maybe you are missing openssl. Did you build it? If not follow the guide inside Andama.pro file.
> OpenSSL is included inside the OpenSSL-1.1.0g folder.
> 
> For linux:
> go inside OpenSSL-x.x folder using the terminal
> type:
> 
>     1. ./config
> 
>     2. make clean
> 
>     3. make
>        this should compile openssl on linux
> 
> 
> Then qmake/clean/rebuild Andama
when I compile the openssl I get:
make[2]: Entering directory '/home/eduardo/Descargas/Andama-Remote-Desktop-develop/src/OpenSSL-1.1.0g'
make[2]: Makefile.shared: No such file or directory
make[2]: *** No rule to make target 'Makefile.shared'.  Stop.
make[2]: Leaving directory '/home/eduardo/Descargas/Andama-Remote-Desktop-develop/src/OpenSSL-1.1.0g'
make[1]: *** [Makefile:642: libcrypto.so] Error 2
make[1]: Leaving directory '/home/eduardo/Descargas/Andama-Remote-Desktop-develop/src/OpenSSL-1.1.0g'
make: *** [Makefile:130: all] Error 2
that's why I downloaded the sources from the openssl site and compiled again and it passes without problems, since the one you include can not compile.

**Comment by eduardoc25** [comment]
> @eduardoc25
> windows compile guide:
> install activeperl - https://www.activestate.com/activeperl
> install nasm - http://www.nasm.us/
> go inside OpenSSL-x.x folder from visual studio 2010 command line prompt
> type :
> 
>     1. perl.exe Configure VC-WIN32
> 
>     2. nmake clean
> 
>     3. nmake
>        this should compile openssl on windows
Yes, in windows I have managed to compile openssl but with perl Configure VC-WIN64A and the MSVC2015 64bits c/c++ ...

**Comment by YiannisBourkelis** [comment]
@eduardoc25 ok, now qmake/clean/rebuild Andama. Does it work?

**Comment by YiannisBourkelis** [comment]
@eduardoc25 keyboard not working yet on the develop branch, but mouse works. If you press a key after connecting to the remote computer it will crash.

**Comment by eduardoc25** [comment]
> @eduardoc25 ok, now qmake/clean/rebuild Andama from within the Qt Creator IDE. Does it work?

It works!

**Comment by eduardoc25** [comment]
>  keyboard not working yet on the develop branch, but mouse works. If you press a key after connecting to the remote computer it will crash.

Oh, then it's correct, that's exactly what happened to me ... So you have some idea of how I can solve it in the development branch ?. Or do I have to try the main branch to make it work?
And by the way, thanks for the answers! You have been very helpful!

**Comment by YiannisBourkelis** [comment]
The develop branch is the most current. I will take a look on the keyboard issue tomorrow if I have some time and I will let you know. Thanks for testing :-)

**Comment by eduardoc25** [comment]
@YiannisBourkelis , perfect !, I'm still in diapers with c / c ++, I'm going to play with what I have and if I find a possible solution I will also let you know (at least I know that the error is not the result of my environment to build the application - problem may be in the code). regards

**Comment by YiannisBourkelis** [comment]
@eduardoc25 ok, keyboard issue fixed.

**Comment by eduardoc25** [comment]
> @eduardoc25 ok, keyboard issue fixed.

How good you are, when I am at home, I try it back! ... By the way, excuse my super English.

**Comment by eduardoc25** [comment]
@YiannisBourkelis, confirmed, the keyboard is working now ... it does not really exhibit the correct keys, but the application no longer ends when you press any key.
