### ISSUE TITLE
Compile Fail On Qt 5.9 and mingw 53_32

### ISSUE THREAD

**Issue by kingofnull** [YiannisBourkelis/Andama-Remote-Desktop#5]
The test server that app compiled with is out of busyness so I try test it locally but I cant compile project and test it. I got Qt 5.9 and mingw 53 on Windows 10 but it seams it can't find Microsoft-Windows functions. 
![alt text](https://preview.ibb.co/naLDSQ/Untitled.png)

I cant find any instruction for compiling on windows so please make one or help me to compile it.

Thanks a lot

**Comment by YiannisBourkelis** [comment]
@kingofnull the dev server is up and running. I have a windows 7 machine with mingw and it compiles fine. I will take a look at this compile issue on Monday.

**Comment by kingofnull** [comment]
I mean the Anmanda itself not the proxy. Anyway I add `win32: LIBS += -lgdi32 -lcomdlg32 -lws2_32` to project file `Andama.pro` and it compiled successfully but when it terminate i get this error:
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: E:\Projects\Qt\Andama-Remote-Desktop-master\src\build-Andama-Desktop_Qt_5_9_1_MinGW_32bit-Debug\debug\Andama.exe



This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.


---------------------------
OK   
---------------------------

**Comment by YiannisBourkelis** [comment]
@kingofnull this might be because some background threads are still running. This is a known issue.

**Comment by kingofnull** [comment]
I there any way to solve it?

**Comment by YiannisBourkelis** [comment]
@kingofnull try to clone the develop branch and let me know if you have the same error on exit

**Comment by kingofnull** [comment]
The develop branch compiles without adding any config but when I close the app the previous error still appears.

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: E:\Projects\Qt\Andama Develope Branch\Andama-Remote-Desktop\src\build-Andama-Desktop_Qt_5_9_1_MinGW_32bit-Debug\debug\Andama.exe



This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.


---------------------------
OK   
---------------------------


And the application output is this:


sendto: No error
sendto: No error
sendto: No error
sendto: No error
sendto: No error
sendto: No error
sendto: No error
Client ID recieved from server: 206500¬1ïن³5
keepalive::run exiting...

screenshotsWorker::run exiting...

AddPortMappingAsyncThread exiting...

Warning: Could not parse stylesheet of object 0x2e9f3e58 (styles\qstylesheetstyle.cpp:1591, QVector<QCss::StyleRule> QStyleSheetStyle::styleRules(const QObject*) const)
Warning: Could not parse stylesheet of object 0x2e9f3e58 (styles\qstylesheetstyle.cpp:1591, QVector<QCss::StyleRule> QStyleSheetStyle::styleRules(const QObject*) const)
Debug: -------------||||  GUI THREAD ||| Thread id inside MainWindow 14772 (../Andama/mainwindow.cpp:369, MainWindow::MainWindow(QWidget*))
Debug: Remote Cotrol BETA - (c) 2015 Yiannis Bourkelis 

 (../Andama/clientsocket.cpp:154, void clientSocket::connectToServer())
Debug: Little endian (../Andama/clientsocket.cpp:58, void _displayEndianness())
Debug: Server protocol: v10.0 (../Andama/clientserverprotocol.cpp:54, void clientServerProtocol::proccessMessage(const std::array<char, 1u>&))
Debug: Thread id inside mymessageRecieved 14772 (../Andama/mainwindow.cpp:620, void MainWindow::mymessageRecieved(const clientServerProtocol*, int, const std::vector<char>&))
Debug: 206500 (../Andama/mainwindow.cpp:624, void MainWindow::mymessageRecieved(const clientServerProtocol*, int, const std::vector<char>&))
Fatal: QThread: Destroyed while thread is still running (thread\qthread.cpp:429, virtual QThread::~QThread())
E:\Projects\Qt\Andama Develope Branch\Andama-Remote-Desktop\src\build-Andama-Desktop_Qt_5_9_1_MinGW_32bit-Debug\debug\Andama.exe exited with code 3

**Comment by kingofnull** [comment]
![image](https://user-images.githubusercontent.com/11198668/30238682-d39aa8a0-9560-11e7-89ba-da070825faa4.png)

![image](https://user-images.githubusercontent.com/11198668/30238678-bf0e2da8-9560-11e7-91d6-ca8e743026ba.png)

**Comment by kingofnull** [comment]
but proxy needs `LIBS += -lws2_32` in project file
