### ISSUE TITLE
Chat support 

### ISSUE THREAD

**Issue by kingofnull** [YiannisBourkelis/Andama-Remote-Desktop#6]
There is any plan to support chat on session?

**Comment by YiannisBourkelis** [comment]
@kingofnull yes, but I first need to implement the remote desktop part.

**Comment by kingofnull** [comment]
remote desktop ? what is it? do you plan use Windows RDP protocol?

**Comment by YiannisBourkelis** [comment]
@kingofnull no I have implemented my own protocol. I mean the remote desktop image/mouse/keyboard
