### ISSUE TITLE
Implement xrdp to increase performance on slow networks

### ISSUE THREAD

**Issue by kingofnull** [YiannisBourkelis/Andama-Remote-Desktop#7]
Xrdp is an open source version Windows RDP protocol which highly optimized for capturing and transferring screen in Ms-Windows. I know it's just an idea and far far away from real solution but it seams very  awesome. Just think about it...

**Comment by kingofnull** [comment]
There is a project that implemented client side 
https://github.com/sailfishos/RemoteDisplay

**Comment by YiannisBourkelis** [comment]
@kingofnull thanks, I will take a look at it
